# Changes here will be overwritten by Copier
_commit: 41c2f2c
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: Help with your BMs
project_name: laxate
python_version_primary: '3.11'
team: the laxate authors
